logging:
  level:
    com.anshuman.workflow: DEBUG
    com.anshuman.workflow.aspect.ProfilingAspect: DEBUG
    org.springframework: INFO
    org.springframework.statemachine: INFO
    org.springframework.statemachine.support: INFO
    org.springframework.statemachine.support.AbstractStateMachine: INFO
    org.springframework.statemachine.support.LifecycleObjectSupport: INFO
    org.springframework.statemachine.support.ReactiveStateMachineExecutor: INFO
    org.springframework.statemachine.support.ReactiveLifecycleManager: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workflow?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
    username: anshuman
    password: anshuman
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-ignored-properties: false
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
    show-sql: true
  main:
    lazy-initialization: false