logging:
  level:
    com.anshuman.workflow: INFO
    org.springframework: INFO
    org.springframework.statemachine: INFO
    org.springframework.statemachine.support: INFO
    org.springframework.statemachine.support.AbstractStateMachine: INFO
    org.springframework.statemachine.support.LifecycleObjectSupport: INFO
    org.springframework.statemachine.support.ReactiveStateMachineExecutor: INFO
    org.springframework.statemachine.support.ReactiveLifecycleManager: INFO

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/workflow?logUnclosedConnections=true&currentSchema=public&reWriteBatchedInserts=true
    username: anshuman
    password: anshuman
  jpa:
    open-in-view: false
    properties:
      hibernate.hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
    show-sql: true
  main:
    lazy-initialization: true