logging:
  level:
    com.anshuman.workflow: DEBUG
    org.springframework: INFO
    org.springframework.statemachine: DEBUG
    org.springframework.statemachine.support: INFO
    org.springframework.statemachine.support.AbstractStateMachine: INFO
    org.springframework.statemachine.support.LifecycleObjectSupport: INFO
    org.springframework.statemachine.support.ReactiveStateMachineExecutor: INFO
    org.springframework.statemachine.support.ReactiveLifecycleManager: INFO

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/Users/anshuman/workspace/Spring/StateMachineDemo/workflow
    username: sa
    password:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
    show-sql: true
  main:
    lazy-initialization: true